networks:
   default:
      external: true
      name: roboshop
services:
   mongodb:
      container_name: mongodb
      image: dockerswaha/mongodb:v1
   catalogue:
      container_name: catalogue
      image: dockerswaha/catalogue:v1
      depends_on:
      - mongodb
   mysql:
      container_name: mysql
      image: dockerswaha/mysql:v1
   user:
      container_name: user
      image: dockerswaha/user:v1
      depends_on:
      - mongodb
      - redis
   cart:
      container_name: cart
      image: dockerswaha/cart:v1
      depends_on:
      - catalogue
      - redis
   redis:
      image: redis
      container_name: redis
   web:
      container_name: web
      image: dockerswaha/web:v1
      ports:
      - "80:80"
      depends_on:
      - catalogue
      - user
      - cart
   shipping:
      container_name: shipping
      image: dockerswaha/shipping:v1
      depends_on:
      - mysql
   rabbitmq:
     image: rabbitmq
     container_name: rabbitmq
     environment:
     - RABBITMQ_DEFAULT_USER=roboshop
     - RABBITMQ_DEFAULT_PASS=roboshop123
   payment:
     image: dockerswaha/payment:v1
     container_name: payment
     depends_on:
     - rabbitmq
     - user
     - cart


